version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres_olist
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver_olist
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
    ports:
      - "8080:8080"
    command: bash -c "pip install pandas sqlalchemy psycopg2-binary && airflow db init && airflow users create --username airflow --password airflow --firstname Ernest --lastname Oppong --role Admin --email yourmail@example.com && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler_olist
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
    command: bash -c "pip install pandas sqlalchemy psycopg2-binary && airflow scheduler"

volumes:
  postgres_data: